TYPE=VIEW
query=select `e`.`id` AS `evento_id`,`e`.`nombre` AS `evento_nombre`,`e`.`fecha_inicio` AS `fecha_inicio`,`e`.`fecha_fin` AS `fecha_fin`,`e`.`estado` AS `evento_estado`,count(distinct `p`.`id`) AS `total_plantillas`,count(distinct `p`.`rol`) AS `roles_con_plantilla`,count(distinct `part`.`id`) AS `total_participantes`,count(distinct `c`.`id`) AS `total_certificados`,count(distinct case when `c`.`tipo_archivo` = \'svg\' then `c`.`id` end) AS `certificados_svg`,count(distinct case when `c`.`tipo_archivo` = \'pdf\' then `c`.`id` end) AS `certificados_pdf`,count(distinct case when `c`.`tipo_archivo` = \'html\' then `c`.`id` end) AS `certificados_html`,round(count(distinct case when `c`.`tipo_archivo` = \'svg\' then `c`.`id` end) / nullif(count(distinct `c`.`id`),0) * 100,1) AS `porcentaje_svg`,max(`p`.`updated_at`) AS `ultima_actualizacion_plantilla` from (((`certificados_idexud`.`eventos` `e` left join `certificados_idexud`.`plantillas_certificados` `p` on(`e`.`id` = `p`.`evento_id`)) left join `certificados_idexud`.`participantes` `part` on(`e`.`id` = `part`.`evento_id`)) left join `certificados_idexud`.`certificados` `c` on(`part`.`id` = `c`.`participante_id`)) group by `e`.`id`,`e`.`nombre`,`e`.`fecha_inicio`,`e`.`fecha_fin`,`e`.`estado` order by `e`.`fecha_inicio` desc
md5=1be2315bdf0474d3eb0da77ed46d2363
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001749742410100125
create-version=2
source=SELECT \n    e.id as evento_id,\n    e.nombre as evento_nombre,\n    e.fecha_inicio,\n    e.fecha_fin,\n    e.estado as evento_estado,\n    COUNT(DISTINCT p.id) as total_plantillas,\n    COUNT(DISTINCT p.rol) as roles_con_plantilla,\n    COUNT(DISTINCT part.id) as total_participantes,\n    COUNT(DISTINCT c.id) as total_certificados,\n    COUNT(DISTINCT CASE WHEN c.tipo_archivo = \'svg\' THEN c.id END) as certificados_svg,\n    COUNT(DISTINCT CASE WHEN c.tipo_archivo = \'pdf\' THEN c.id END) as certificados_pdf,\n    COUNT(DISTINCT CASE WHEN c.tipo_archivo = \'html\' THEN c.id END) as certificados_html,\n    ROUND(\n        (COUNT(DISTINCT CASE WHEN c.tipo_archivo = \'svg\' THEN c.id END) / \n         NULLIF(COUNT(DISTINCT c.id), 0)) * 100, 1\n    ) as porcentaje_svg,\n    MAX(p.updated_at) as ultima_actualizacion_plantilla\nFROM eventos e\nLEFT JOIN plantillas_certificados p ON e.id = p.evento_id\nLEFT JOIN participantes part ON e.id = part.evento_id\nLEFT JOIN certificados c ON part.id = c.participante_id\nGROUP BY e.id, e.nombre, e.fecha_inicio, e.fecha_fin, e.estado\nORDER BY e.fecha_inicio DESC
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `e`.`id` AS `evento_id`,`e`.`nombre` AS `evento_nombre`,`e`.`fecha_inicio` AS `fecha_inicio`,`e`.`fecha_fin` AS `fecha_fin`,`e`.`estado` AS `evento_estado`,count(distinct `p`.`id`) AS `total_plantillas`,count(distinct `p`.`rol`) AS `roles_con_plantilla`,count(distinct `part`.`id`) AS `total_participantes`,count(distinct `c`.`id`) AS `total_certificados`,count(distinct case when `c`.`tipo_archivo` = \'svg\' then `c`.`id` end) AS `certificados_svg`,count(distinct case when `c`.`tipo_archivo` = \'pdf\' then `c`.`id` end) AS `certificados_pdf`,count(distinct case when `c`.`tipo_archivo` = \'html\' then `c`.`id` end) AS `certificados_html`,round(count(distinct case when `c`.`tipo_archivo` = \'svg\' then `c`.`id` end) / nullif(count(distinct `c`.`id`),0) * 100,1) AS `porcentaje_svg`,max(`p`.`updated_at`) AS `ultima_actualizacion_plantilla` from (((`certificados_idexud`.`eventos` `e` left join `certificados_idexud`.`plantillas_certificados` `p` on(`e`.`id` = `p`.`evento_id`)) left join `certificados_idexud`.`participantes` `part` on(`e`.`id` = `part`.`evento_id`)) left join `certificados_idexud`.`certificados` `c` on(`part`.`id` = `c`.`participante_id`)) group by `e`.`id`,`e`.`nombre`,`e`.`fecha_inicio`,`e`.`fecha_fin`,`e`.`estado` order by `e`.`fecha_inicio` desc
mariadb-version=100432
