TYPE=VIEW
query=select `p`.`id` AS `id`,`p`.`evento_id` AS `evento_id`,`p`.`rol` AS `rol`,`p`.`roles_aplicables` AS `roles_aplicables`,`p`.`nombre_plantilla` AS `nombre_plantilla`,`p`.`archivo_plantilla` AS `archivo_plantilla`,`p`.`variables_disponibles` AS `variables_disponibles`,`p`.`ancho` AS `ancho`,`p`.`alto` AS `alto`,`p`.`created_at` AS `created_at`,`p`.`updated_at` AS `updated_at`,`e`.`nombre` AS `evento_nombre`,`e`.`fecha_inicio` AS `fecha_inicio`,`e`.`fecha_fin` AS `fecha_fin`,`e`.`entidad_organizadora` AS `entidad_organizadora`,`e`.`modalidad` AS `modalidad`,(select count(0) from `certificados_idexud`.`participantes` `part` where `part`.`evento_id` = `e`.`id` and (find_in_set(`part`.`rol`,`p`.`roles_aplicables`) > 0 or `p`.`roles_aplicables` = \'general\' or `p`.`roles_aplicables` like \'%general%\')) AS `participantes_rol`,(select count(0) from (`certificados_idexud`.`certificados` `c` join `certificados_idexud`.`participantes` `part` on(`c`.`participante_id` = `part`.`id`)) where `part`.`evento_id` = `e`.`id` and (find_in_set(`part`.`rol`,`p`.`roles_aplicables`) > 0 or `p`.`roles_aplicables` = \'general\' or `p`.`roles_aplicables` like \'%general%\')) AS `certificados_generados`,(select count(0) from (`certificados_idexud`.`certificados` `c` join `certificados_idexud`.`participantes` `part` on(`c`.`participante_id` = `part`.`id`)) where `part`.`evento_id` = `e`.`id` and (find_in_set(`part`.`rol`,`p`.`roles_aplicables`) > 0 or `p`.`roles_aplicables` = \'general\' or `p`.`roles_aplicables` like \'%general%\') and `c`.`tipo_archivo` = \'svg\') AS `certificados_svg` from (`certificados_idexud`.`plantillas_certificados` `p` join `certificados_idexud`.`eventos` `e` on(`p`.`evento_id` = `e`.`id`))
md5=4412a79babd3aac5475673985a08e3d6
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001750267683786098
create-version=2
source=SELECT \n    p.*,\n    e.nombre as evento_nombre,\n    e.fecha_inicio,\n    e.fecha_fin,\n    e.entidad_organizadora,\n    e.modalidad,\n    -- Contar participantes para cualquiera de los roles aplicables\n    (\n        SELECT COUNT(*) \n        FROM participantes part \n        WHERE part.evento_id = e.id \n        AND (\n            FIND_IN_SET(part.rol, p.roles_aplicables) > 0 \n            OR p.roles_aplicables = \'general\'\n            OR p.roles_aplicables LIKE \'%general%\'\n        )\n    ) as participantes_rol,\n    -- Contar certificados generados para los roles aplicables\n    (\n        SELECT COUNT(*) \n        FROM certificados c \n        JOIN participantes part ON c.participante_id = part.id \n        WHERE part.evento_id = e.id \n        AND (\n            FIND_IN_SET(part.rol, p.roles_aplicables) > 0 \n            OR p.roles_aplicables = \'general\'\n            OR p.roles_aplicables LIKE \'%general%\'\n        )\n    ) as certificados_generados,\n    -- Contar certificados SVG para los roles aplicables\n    (\n        SELECT COUNT(*) \n        FROM certificados c \n        JOIN participantes part ON c.participante_id = part.id \n        WHERE part.evento_id = e.id \n        AND (\n            FIND_IN_SET(part.rol, p.roles_aplicables) > 0 \n            OR p.roles_aplicables = \'general\'\n            OR p.roles_aplicables LIKE \'%general%\'\n        )\n        AND c.tipo_archivo = \'svg\'\n    ) as certificados_svg\nFROM plantillas_certificados p\nJOIN eventos e ON p.evento_id = e.id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `p`.`id` AS `id`,`p`.`evento_id` AS `evento_id`,`p`.`rol` AS `rol`,`p`.`roles_aplicables` AS `roles_aplicables`,`p`.`nombre_plantilla` AS `nombre_plantilla`,`p`.`archivo_plantilla` AS `archivo_plantilla`,`p`.`variables_disponibles` AS `variables_disponibles`,`p`.`ancho` AS `ancho`,`p`.`alto` AS `alto`,`p`.`created_at` AS `created_at`,`p`.`updated_at` AS `updated_at`,`e`.`nombre` AS `evento_nombre`,`e`.`fecha_inicio` AS `fecha_inicio`,`e`.`fecha_fin` AS `fecha_fin`,`e`.`entidad_organizadora` AS `entidad_organizadora`,`e`.`modalidad` AS `modalidad`,(select count(0) from `certificados_idexud`.`participantes` `part` where `part`.`evento_id` = `e`.`id` and (find_in_set(`part`.`rol`,`p`.`roles_aplicables`) > 0 or `p`.`roles_aplicables` = \'general\' or `p`.`roles_aplicables` like \'%general%\')) AS `participantes_rol`,(select count(0) from (`certificados_idexud`.`certificados` `c` join `certificados_idexud`.`participantes` `part` on(`c`.`participante_id` = `part`.`id`)) where `part`.`evento_id` = `e`.`id` and (find_in_set(`part`.`rol`,`p`.`roles_aplicables`) > 0 or `p`.`roles_aplicables` = \'general\' or `p`.`roles_aplicables` like \'%general%\')) AS `certificados_generados`,(select count(0) from (`certificados_idexud`.`certificados` `c` join `certificados_idexud`.`participantes` `part` on(`c`.`participante_id` = `part`.`id`)) where `part`.`evento_id` = `e`.`id` and (find_in_set(`part`.`rol`,`p`.`roles_aplicables`) > 0 or `p`.`roles_aplicables` = \'general\' or `p`.`roles_aplicables` like \'%general%\') and `c`.`tipo_archivo` = \'svg\') AS `certificados_svg` from (`certificados_idexud`.`plantillas_certificados` `p` join `certificados_idexud`.`eventos` `e` on(`p`.`evento_id` = `e`.`id`))
mariadb-version=100432
